version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "7777:80"
    container_name: nginx_server
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: app_project

  db:
    image: postgres
    container_name: db
    volumes:
      - ./postgresql/data:/var/www/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdminPanel
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: manul@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
